# """
# AI Engine - AI-Generated Code Detector

# Uses 4 detection strategies:
#   1. ML Model (RoBERTa-based, optional / lazy-loaded)
#   2. Pattern Analysis (AI-typical comment/naming conventions)
#   3. Style Consistency (humans have ~5-15% inconsistency; AI is near-perfect)
#   4. Complexity Variance (AI produces uniformly moderate complexity)
# """
# import ast
# import logging
# import re
# import statistics
# from typing import Any, Dict, List, Optional

# logger = logging.getLogger(__name__)

# # numpy is optional – used only for convenience; pure-Python fallbacks provided
# try:
#     import numpy as _np
#     _HAS_NUMPY = True
# except ImportError:  # pragma: no cover
#     _np = None  # type: ignore[assignment]
#     _HAS_NUMPY = False


# # ---------------------------------------------------------------------------
# # Singleton ML model loader
# # ---------------------------------------------------------------------------
# _ml_model_instance: Optional[Any] = None
# _ml_tokenizer_instance: Optional[Any] = None


# def _get_ml_model():
#     """Lazy-load RoBERTa detector (CPU-safe)."""
#     global _ml_model_instance, _ml_tokenizer_instance
#     if _ml_model_instance is not None:
#         return _ml_tokenizer_instance, _ml_model_instance

#     try:
#         import torch
#         from transformers import AutoModelForSequenceClassification, AutoTokenizer

#         model_name = "roberta-base-openai-detector"
#         logger.info(f"Loading AI detection model: {model_name}")
#         _ml_tokenizer_instance = AutoTokenizer.from_pretrained(model_name)
#         _ml_model_instance = AutoModelForSequenceClassification.from_pretrained(model_name)
#         _ml_model_instance.eval()
#         logger.info("AI detection model loaded successfully.")
#     except Exception as e:
#         logger.warning(f"AI detection model unavailable ({e}). Falling back to heuristics.")
#         _ml_model_instance = None
#         _ml_tokenizer_instance = None

#     return _ml_tokenizer_instance, _ml_model_instance


# # ---------------------------------------------------------------------------
# # Main class
# # ---------------------------------------------------------------------------
# class AICodeDetector:
#     """
#     Detects if code was generated by AI tools (ChatGPT, GitHub Copilot, etc.).
#     Uses 5 detection strategies: ML model, pattern analysis, style consistency,
#     complexity variance, and structural analysis.
#     """

#     WEIGHTS = {
#         "ml_model": 0.35,
#         "pattern_analysis": 0.20,
#         "style_consistency": 0.20,
#         "complexity_analysis": 0.10,
#         "structural_analysis": 0.15,
#     }

#     THRESHOLD = 0.75  # Probability >= this → flagged as AI-generated

#     def analyze(self, code: str, file_path: Optional[str] = None) -> Dict[str, Any]:
#         """
#         Comprehensive AI-generated code detection.

#         Args:
#             code: Source code string.
#             file_path: Optional path (used for logging).

#         Returns:
#             Dict with probability, verdict, confidence, detection details, and flags.
#         """
#         if not code or not code.strip():
#             return self._empty_response("Empty code provided")

#         try:
#             ml_score = self._ml_detection(code)
#             pattern_score = self._pattern_analysis(code)
#             style_score = self._style_consistency_check(code)
#             complexity_score = self._complexity_analysis(code)
#             structural_score = self._structural_analysis(code)

#             # Round values to 4 decimal places
#             def _r(v): return float(round(float(v), 4))

#             # Round values to 4 decimal places using a robust helper
#             def _r(v) -> float:
#                 try:
#                     return float("{:.4f}".format(float(v)))
#                 except (ValueError, TypeError):
#                     return 0.0

#             detection_details: Dict[str, float] = {
#                 "ml_detection": _r(ml_score),
#                 "pattern_score": _r(pattern_score),
#                 "style_score": _r(style_score),
#                 "complexity_score": _r(complexity_score),
#                 "structural_score": _r(structural_score),
#             }

#             raw_prob = (
#                 ml_score * self.WEIGHTS["ml_model"]
#                 + pattern_score * self.WEIGHTS["pattern_analysis"]
#                 + style_score * self.WEIGHTS["style_consistency"]
#                 + complexity_score * self.WEIGHTS["complexity_analysis"]
#                 + structural_score * self.WEIGHTS["structural_analysis"]
#             )
#             ai_probability = _r(max(0.0, min(1.0, raw_prob)))

#             confidence = self._calculate_confidence(detection_details)
#             verdict = self._get_verdict(ai_probability)
#             flags = self._get_specific_flags(code, detection_details)

#             return {
#                 "ai_generated_probability": ai_probability,
#                 "verdict": verdict,
#                 "confidence": _r(confidence),
#                 "detection_details": detection_details,
#                 "flags": flags,
#             }

#         except Exception as e:
#             logger.error(f"AI detection error for {file_path}: {e}")
#             return self._empty_response(str(e))

#     # ------------------------------------------------------------------
#     # Strategy 1: ML Model
#     # ------------------------------------------------------------------
#     def _ml_detection(self, code: str) -> float:
#         """
#         Use RoBERTa model to detect AI-generated code.
#         Tokenizes the first 512 tokens and runs inference.
#         Returns 0.5 (neutral) when model is unavailable.
#         """
#         tokenizer, model = _get_ml_model()
#         if model is None or tokenizer is None:
#             return 0.5  # Neutral – heuristics will dominate

#         try:
#             import torch

#             inputs = tokenizer(
#                 code,
#                 return_tensors="pt",
#                 max_length=512,
#                 truncation=True,
#                 padding=True,
#             )
#             with torch.no_grad():
#                 logits = model(**inputs).logits
#                 probs = torch.softmax(logits, dim=-1)
#                 # Label 1 = "generated", label 0 = "real"
#                 ai_prob = float(probs[0][1].item())
#             return ai_prob
#         except Exception as e:
#             logger.warning(f"ML inference failed: {e}")
#             return 0.5

#     # ------------------------------------------------------------------
#     # Strategy 2: Pattern Analysis
#     # ------------------------------------------------------------------
#     def _pattern_analysis(self, code: str) -> float:
#         """
#         Analyze code for patterns typical of AI-generated output.
#         Returns a 0-1 score (higher = more AI-like).
#         """
#         signals: List[float] = []

#         # Perfect comment formatting
#         if self._check_perfect_comments(code):
#             signals.append(0.85)

#         # Overly verbose names
#         if self._check_verbose_names(code):
#             signals.append(0.75)

#         # Comprehensive docstrings on ALL functions/classes
#         docstring_coverage = self._docstring_coverage(code)
#         signals.append(docstring_coverage)

#         # Check for explanatory inline comments typical of AI
#         inline_comment_density = self._inline_comment_density(code)
#         signals.append(min(1.0, inline_comment_density * 2.5))

#         # Check for conversational AI boilerplate text
#         if self._check_ai_boilerplate_text(code):
#             signals.append(1.0)  # Very strong signal

#         # Pure-Python mean (no numpy dependency)
#         return float(sum(signals) / len(signals)) if signals else 0.5

#     def _check_perfect_comments(self, code: str) -> bool:
#         """Check for AI-style perfectly formatted comments."""
#         comment_lines = [
#             l.strip() for l in code.splitlines() if l.strip().startswith("#")
#         ]
#         if not comment_lines:
#             return False
#         # AI comments tend to start with capital letter and end without period
#         capitalised = sum(
#             1 for c in comment_lines if c.lstrip("#").strip()[:1].isupper()
#         )
#         return (capitalised / len(comment_lines)) > 0.85

#     def _check_verbose_names(self, code: str) -> bool:
#         """Check for AI-style overly descriptive identifiers."""
#         identifiers = re.findall(r"\b([a-z][a-z0-9_]{15,})\b", code)
#         if not identifiers:
#             return False
#         return len(identifiers) > 5  # More than 5 very long names is suspicious

#     def _docstring_coverage(self, code: str) -> float:
#         """Fraction of functions/classes that have docstrings (AI tends to 100%)."""
#         try:
#             tree = ast.parse(code)
#         except SyntaxError:
#             return 0.5

#         callables = [
#             n
#             for n in ast.walk(tree)
#             if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
#         ]
#         if not callables:
#             return 0.0

#         with_docs = sum(
#             1 for n in callables if ast.get_docstring(n)
#         )
#         ratio = with_docs / len(callables)
#         # Humans rarely document 100%; very suspicious if > 90%
#         return ratio if ratio > 0.85 else ratio * 0.5

#     def _inline_comment_density(self, code: str) -> float:
#         """Fraction of code lines with an inline comment."""
#         lines = [l for l in code.splitlines() if l.strip()]
#         if not lines:
#             return 0.0
#         inline = sum(1 for l in lines if "#" in l and not l.strip().startswith("#"))
#         return inline / len(lines)

#     # ------------------------------------------------------------------
#     # Strategy 3: Style Consistency
#     # ------------------------------------------------------------------
#     def _style_consistency_check(self, code: str) -> float:
#         """
#         Check if style is TOO consistent (a strong AI indicator).
#         Humans have ~5-15% natural inconsistency.
#         Returns 0-1   (higher = more AI-like).
#         """
#         quote_consistency = self._check_quote_consistency(code)
#         spacing_consistency = self._check_spacing_consistency(code)
#         naming_consistency = self._naming_convention_consistency(code)

#         avg_consistency = float(
#             statistics.mean([quote_consistency, spacing_consistency, naming_consistency])
#         )

#         # Consistency > 0.95 → very suspicious
#         if avg_consistency > 0.95:
#             return 0.9
#         elif avg_consistency > 0.85:
#             return 0.65
#         elif avg_consistency > 0.70:
#             return 0.40
#         else:
#             return 0.20

#     def _check_quote_consistency(self, code: str) -> float:
#         """Calculate string-quote style consistency (0-1)."""
#         single = len(re.findall(r"'[^']*'", code))
#         double = len(re.findall(r'"[^"]*"', code))
#         total = single + double
#         if total == 0:
#             return 1.0
#         return max(single, double) / total

#     def _check_spacing_consistency(self, code: str) -> float:
#         """Calculate operator spacing consistency (0-1)."""
#         spaced = len(re.findall(r"\w\s+=\s+\w", code))
#         nospaced = len(re.findall(r"\w=\w", code))
#         total = spaced + nospaced
#         if total == 0:
#             return 1.0
#         return max(spaced, nospaced) / total

#     def _naming_convention_consistency(self, code: str) -> float:
#         """Check how uniformly snake_case is used (0-1)."""
#         identifiers = re.findall(r"\b([a-zA-Z_][a-zA-Z0-9_]{2,})\b", code)
#         if not identifiers:
#             return 1.0
#         snake = sum(1 for i in identifiers if "_" in i and i == i.lower())
#         return snake / len(identifiers)

#     # ------------------------------------------------------------------
#     # Strategy 4: Complexity Variance
#     # ------------------------------------------------------------------
#     def _complexity_analysis(self, code: str) -> float:
#         """
#         Detect uniform cyclomatic complexity (AI indicator).
#         Low variance across functions = AI-generated.
#         Returns 0-1 (higher = more AI-like / more uniform).
#         """
#         try:
#             import radon.complexity as rc

#             blocks = rc.cc_visit(code)
#             complexities = [b.complexity for b in blocks]

#             if len(complexities) < 2:
#                 return 0.5  # Not enough data

#             variance = statistics.variance(complexities)

#             # Very low variance (< 2) across functions is suspicious
#             if variance < 1.0:
#                 return 0.85
#             elif variance < 3.0:
#                 return 0.60
#             elif variance < 6.0:
#                 return 0.35
#             else:
#                 return 0.15

#         except Exception:
#             return 0.5

#     # ------------------------------------------------------------------
#     # Strategy 5: Structural Analysis
#     # ------------------------------------------------------------------
#     def _structural_analysis(self, code: str) -> float:
#         """
#         Analyze structural patterns typical of AI (e.g., rigorous type hinting,
#         heavy use of comprehensive exception handling, specific AST traits).
#         """
#         try:
#             tree = ast.parse(code)
#         except SyntaxError:
#             return 0.5
            
#         signals: List[float] = []
#         signals.append(self._type_hint_density(tree))
#         signals.append(self._boilerplate_exception_handling(tree))
#         signals.append(self._comprehension_preference(tree))
#         signals.append(self._builtin_shadowing_check(tree))
#         signals.append(self._dead_code_signal(code))
        
#         return float(sum(signals) / len(signals)) if signals else 0.5

#     def _type_hint_density(self, tree: ast.AST) -> float:
#         """AI almost always uses type hints. Returns 0-1."""
#         typed_args: int = 0
#         total_args: int = 0
        
#         for node in ast.walk(tree):
#             if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
#                 for arg in node.args.args:
#                     if arg.arg != 'self':
#                         total_args += 1
#                         if arg.annotation is not None:
#                             typed_args += 1
        
#         if total_args == 0:
#             return 0.5
            
#         ratio = float(typed_args) / float(total_args)
#         return ratio if ratio > 0.8 else ratio * 0.5

#     def _boilerplate_exception_handling(self, tree: ast.AST) -> float:
#         """AI often adds generic try... except Exception as e blocks."""
#         try_blocks = [n for n in ast.walk(tree) if isinstance(n, ast.Try)]
#         if not try_blocks:
#             return 0.2
            
#         generic_excepts: int = 0
#         for t in try_blocks:
#             for handler in t.handlers:
#                 h_type = handler.type
#                 if isinstance(h_type, ast.Name) and h_type.id == 'Exception':
#                     generic_excepts += 1
                    
#         ratio = float(generic_excepts) / float(len(try_blocks))
#         return ratio if ratio > 0.5 else 0.3

#     def _comprehension_preference(self, tree: ast.AST) -> float:
#         """AI prefers list/dict comprehensions over simple loops."""
#         loops = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.For, ast.While)))
#         comps = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.ListComp, ast.DictComp, ast.SetComp, ast.GeneratorExp)))
        
#         total = loops + comps
#         if total == 0:
#             return 0.5
            
#         # AI often hits a 1:1 or higher ratio for simple tasks
#         ratio = comps / total if total > 0 else 0.5
#         return min(1.0, ratio * 1.25)

#     def _builtin_shadowing_check(self, tree: ast.AST) -> float:
#         """
#         Humans often shadow built-ins (e.g. list, id, sum). 
#         AI is generally trained to avoid this unless specifically bad prompting.
#         Returns low AI score if shadowing is found.
#         """
#         builtins = {'list', 'id', 'sum', 'min', 'max', 'type', 'dir', 'dict', 'set', 'map', 'filter'}
#         shadowed = 0
#         total_assigns = 0
#         for node in ast.walk(tree):
#             if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
#                 total_assigns += 1
#                 if node.id in builtins:
#                     shadowed += 1
                    
#         if total_assigns == 0:
#             return 0.5
            
#         # If shadowing found, score lower for AI
#         if shadowed > 0:
#             return 0.1  # Strong human indicator
#         return 0.7  # "Perfect" avoidance is an AI indicator

#     def _dead_code_signal(self, code: str) -> float:
#         """
#         Check for 'dead' blocks like large commented-out code segments.
#         Humans leave these often; AI produces clean outputs.
#         """
#         lines = code.splitlines()
#         commented_code_lines: int = 0
#         for line in lines:
#             trimmed = line.strip()
#             # Heuristic: long comments ending in symbols typical of code
#             if trimmed.startswith("#") and len(trimmed) > 15:
#                 if any(trimmed.endswith(s) for s in [':', ')', '}', ']', ';']):
#                     commented_code_lines += 1
        
#         if len(lines) == 0:
#             return 0.5
            
#         density = float(commented_code_lines) / float(len(lines))
#         # High dead code density = Very Human
#         if density > 0.05:
#             return 0.1
#         return 0.6 # Clean code is slight AI indicator

#     def _check_ai_boilerplate_text(self, code: str) -> bool:
#         """Check for accidental copy-paste of ChatGPT conversational responses."""
#         boilerplate = [
#             r"as an ai (language )?model",
#             r"certainly! here is",
#             r"here is the (code|implementation)",
#             r"please note that",
#             r"in this implementation",
#             r"hope this helps",
#             r"feel free to (ask|modify)",
#             r"i cannot (fulfill|provide)"
#         ]
#         lower_code = code.lower()
#         for b in boilerplate:
#             if re.search(b, lower_code):
#                 return True
#         return False

#     # ------------------------------------------------------------------
#     # Helpers
#     # ------------------------------------------------------------------
#     def _get_verdict(self, probability: float) -> str:
#         if probability >= 0.80:
#             return "LIKELY_AI_GENERATED"
#         elif probability >= 0.60:
#             return "POSSIBLY_AI_ASSISTED"
#         elif probability >= 0.40:
#             return "UNCERTAIN"
#         elif probability >= 0.20:
#             return "POSSIBLY_HUMAN"
#         else:
#             return "LIKELY_HUMAN"

#     def _calculate_confidence(self, detection_details: Dict[str, float]) -> float:
#         """
#         Confidence = 1 - normalised standard deviation across strategy scores.
#         Low variance in scores → strategies agree → high confidence.
#         """
#         scores = list(detection_details.values())
#         if len(scores) < 2:
#             return 0.5
#         std = statistics.stdev(scores)
#         # Normalise: std of 0 → confidence 1.0 ; std of 0.5 (max on 0-1) → confidence 0.0
#         confidence = max(0.0, 1.0 - (std * 2))
#         return confidence

#     def _get_specific_flags(
#         self, code: str, detection_details: Dict[str, float]
#     ) -> List[str]:
#         """Identify specific red flags found in the code."""
#         flags: List[str] = []

#         if detection_details.get("pattern_score", 0) >= 0.70:
#             flags.append("AI-typical comment patterns detected")

#         if self._check_verbose_names(code):
#             flags.append("Overly verbose variable/function names detected")

#         if detection_details.get("style_score", 0) >= 0.70:
#             flags.append("Suspiciously perfect code formatting")

#         if detection_details.get("complexity_score", 0) >= 0.70:
#             flags.append("Uniform complexity across functions (low variance)")

#         if self._docstring_coverage(code) >= 0.90:
#             flags.append("All functions have docstrings (atypical for human code)")

#         if detection_details.get("ml_detection", 0.5) >= 0.70:
#             flags.append("ML model classifies code as likely AI-generated")

#         if detection_details.get("structural_score", 0) >= 0.75:
#             flags.append("Heavy use of type-hints and AI-like code structures")

#         if self._check_ai_boilerplate_text(code):
#             flags.append("Contains conversational dialogue text typically emitted by AI")

#         return flags

#     def _empty_response(self, reason: str) -> Dict[str, Any]:
#         return {
#             "ai_generated_probability": 0.0,
#             "verdict": "UNCERTAIN",
#             "confidence": 0.0,
#             "detection_details": {
#                 "ml_detection": 0.5,
#                 "pattern_score": 0.0,
#                 "style_score": 0.0,
#                 "complexity_score": 0.0,
#                 "structural_score": 0.0,
#             },
#             "flags": [],
#             "error": reason,
#         }






"""
AI Engine - AI-Generated Code Detector (v2)

PRIMARY signal: perplexity + burstiness from a causal code-LLM.
  This is the same family of technique GPTZero-style detectors use for
  prose, applied to code: AI-generated tokens are, on average, more
  "predictable" (lower perplexity) and more uniformly predictable
  (lower burstiness / less variance in surprise) to a language model
  than human-written tokens, which include more idiosyncratic choices.

SECONDARY signals: pattern/style/structural heuristics.
  These are kept as *supporting* evidence only, at low weight, because
  many of them (docstrings, type hints, formatting consistency) are
  also produced by course style guides, linters, and IDE auto-formatters
  -- they are NOT reliable AI/human discriminators on their own for
  graded coursework, and treating them as co-equal to real evidence is
  what made the previous version unreliable.

IMPORTANT: No AI-code detector is highly reliable. Treat this score as
a triage signal for human review, never as an automatic verdict.
The default perplexity anchors below are rough starting points -- you
MUST recalibrate them against your own labeled samples (see
`calibrate_from_samples` at the bottom) before trusting absolute scores.
"""
import ast
import logging
import math
import re
import statistics
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Singleton causal code-LM loader (used for perplexity/burstiness)
# ---------------------------------------------------------------------------
_lm_model_instance: Optional[Any] = None
_lm_tokenizer_instance: Optional[Any] = None

# IMPORTANT: the judge model must be at least as capable as whatever
# generated the code you're checking, or it can't tell the code is
# "predictable" -- a weak model finds GPT-4/Claude-quality code just as
# surprising as human code, and everything reads as "human."
# 350M-class models are too weak for this in practice. 1B+ code-specific
# models are the practical floor; bigger is better if you have the compute.
#   - "deepseek-ai/deepseek-coder-1.3b-base"  <- default: good accuracy/CPU balance
#   - "bigcode/starcoder2-3b"                  <- stronger, multi-language, wants a GPU
#   - "bigcode/starcoder2-7b" / larger          <- best accuracy, needs a real GPU
_LM_MODEL_NAME = "deepseek-ai/deepseek-coder-1.3b-base"
_MAX_CHUNK_TOKENS = 512


def _get_lm() -> Tuple[Optional[Any], Optional[Any]]:
    """Lazy-load the causal code LM used for perplexity scoring."""
    global _lm_model_instance, _lm_tokenizer_instance
    if _lm_model_instance is not None:
        return _lm_tokenizer_instance, _lm_model_instance

    try:
        from transformers import AutoModelForCausalLM, AutoTokenizer

        logger.info(f"Loading code LM for perplexity scoring: {_LM_MODEL_NAME}")
        _lm_tokenizer_instance = AutoTokenizer.from_pretrained(_LM_MODEL_NAME)
        _lm_model_instance = AutoModelForCausalLM.from_pretrained(_LM_MODEL_NAME)
        _lm_model_instance.eval()
        logger.info("Code LM loaded successfully.")
    except Exception as e:
        logger.warning(f"Code LM unavailable ({e}). Perplexity scoring disabled.")
        _lm_model_instance = None
        _lm_tokenizer_instance = None

    return _lm_tokenizer_instance, _lm_model_instance


def _token_nlls(code: str, tokenizer, model, max_len: int = _MAX_CHUNK_TOKENS) -> List[float]:
    """
    Return per-token negative log-likelihoods for `code` under `model`.

    Files longer than max_len are split into sequential, non-overlapping
    chunks (each chunk's model context resets at the chunk boundary --
    a small accuracy cost for a large simplicity/speed win; fine for
    file-level scoring).
    """
    import torch

    enc = tokenizer(code, return_tensors="pt", truncation=False)
    input_ids = enc["input_ids"][0]
    n = input_ids.size(0)
    if n < 2:
        return []

    nlls: List[float] = []
    for start in range(0, n, max_len):
        chunk = input_ids[start:start + max_len]
        if chunk.size(0) < 2:
            continue
        chunk = chunk.unsqueeze(0)
        with torch.no_grad():
            out = model(chunk)
            logits = out.logits[0][:-1, :]
            labels = chunk[0][1:]
            log_probs = torch.log_softmax(logits, dim=-1)
            token_nll = -log_probs[range(labels.size(0)), labels]
        nlls.extend(token_nll.tolist())

    return nlls


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------
class AICodeDetector:
    """
    Estimates the likelihood that a code file was AI-generated.

    Score = weighted blend of perplexity/burstiness (primary) and
    pattern/style/structural heuristics (secondary), with a hard
    override for accidental AI-chat boilerplate text.
    """

    # Weights used when the perplexity model IS available.
    WEIGHTS = {
        "perplexity": 0.65,
        "pattern_analysis": 0.08,
        "style_consistency": 0.07,
        "complexity_analysis": 0.05,
        "structural_analysis": 0.15,
    }
    # Weights are renormalized to 1.0 at scoring time (see analyze()), so
    # these are relative, not absolute.

    # --- Perplexity/burstiness calibration (Gaussian per class) ------------
    # STARTING POINTS ONLY -- these are placeholders, not measured values.
    # Run calibrate_from_samples() against your own labeled human/AI code
    # (same assignment types your platform actually scores) and replace
    # this dict with what you measure. Unlike a single anchor point, this
    # models each class as a distribution (mean + spread), which is what
    # actually lets values that fall outside the "expected" range still
    # get classified sensibly instead of just being clipped to 0 or 1.
    CALIBRATION = {
        "ppl_human_mean": 12.0, "ppl_human_std": 4.5,
        "ppl_ai_mean": 4.0, "ppl_ai_std": 1.8,
        "burst_human_mean": 3.0, "burst_human_std": 1.0,
        "burst_ai_mean": 1.0, "burst_ai_std": 0.5,
    }

    MIN_TOKENS_FOR_PERPLEXITY = 20  # below this, perplexity is too noisy to trust

    THRESHOLD = 0.75  # probability >= this -> flagged as AI-generated

    # ------------------------------------------------------------------
    def analyze(self, code: str, file_path: Optional[str] = None) -> Dict[str, Any]:
        """Comprehensive AI-generated code detection for a single file."""
        if not code or not code.strip():
            return self._empty_response("Empty code provided")

        try:
            ppl_result = self._perplexity_score(code)
            pattern_score = self._pattern_analysis(code)
            style_score = self._style_consistency_check(code)
            complexity_score = self._complexity_analysis(code)
            structural_score = self._structural_analysis(code)

            def _r(v) -> float:
                try:
                    return float("{:.4f}".format(float(v)))
                except (ValueError, TypeError):
                    return 0.0

            detection_details: Dict[str, Any] = {
                "perplexity_score": _r(ppl_result["score"]) if ppl_result["available"] else None,
                "perplexity_raw": _r(ppl_result["perplexity"]) if ppl_result["perplexity"] is not None else None,
                "burstiness_raw": _r(ppl_result["burstiness"]) if ppl_result["burstiness"] is not None else None,
                "pattern_score": _r(pattern_score),
                "style_score": _r(style_score),
                "complexity_score": _r(complexity_score),
                "structural_score": _r(structural_score),
            }

            # Build the active weight set: drop perplexity if unavailable
            # (or too little code to trust it) instead of silently defaulting
            # it to 0.5 and letting it bias the average.
            active_weights = dict(self.WEIGHTS)
            if not ppl_result["available"]:
                del active_weights["perplexity"]
            total_w = sum(active_weights.values())
            norm_weights = {k: v / total_w for k, v in active_weights.items()}

            component_scores = {
                "perplexity": ppl_result["score"],
                "pattern_analysis": pattern_score,
                "style_consistency": style_score,
                "complexity_analysis": complexity_score,
                "structural_analysis": structural_score,
            }

            raw_prob = sum(
                component_scores[k] * w for k, w in norm_weights.items()
            )

            if not ppl_result["available"]:
                # No primary evidence -- these heuristics alone are too weak
                # to justify a confident-looking score in either direction.
                # Shrink toward 0.5 (uncertain) rather than letting a mildly
                # low heuristic average masquerade as "likely human."
                raw_prob = 0.5 + (raw_prob - 0.5) * 0.4

            ai_probability = _r(max(0.0, min(1.0, raw_prob)))

            # Hard override: accidental AI-chat boilerplate is near-certain
            # evidence and shouldn't be diluted by an average.
            boilerplate_hit = self._check_ai_boilerplate_text(code)
            if boilerplate_hit:
                ai_probability = max(ai_probability, 0.95)

            confidence = self._calculate_confidence(
                detection_details, ppl_result["available"], code
            )
            verdict = self._get_verdict(ai_probability)
            flags = self._get_specific_flags(code, detection_details, boilerplate_hit)

            return {
                "ai_generated_probability": ai_probability,
                "verdict": verdict,
                "confidence": _r(confidence),
                "detection_details": detection_details,
                "flags": flags,
                "perplexity_model_used": ppl_result["available"],
            }

        except Exception as e:
            logger.error(f"AI detection error for {file_path}: {e}")
            return self._empty_response(str(e))

    # ------------------------------------------------------------------
    # Project-level convenience: score a whole extracted submission
    # ------------------------------------------------------------------
    def analyze_project(self, files: Dict[str, str]) -> Dict[str, Any]:
        """
        Score every file in an extracted, cleaned submission (path -> code)
        and roll up into a project-level result. Weight each file's
        contribution by its token count so short config/init files don't
        skew the result as much as large source files.

        NOTE: run this only on already-cleaned files -- strip
        node_modules/venv/vendored/generated code before calling this,
        or you'll get meaningless results (see the zip-preprocessing step
        discussed earlier in this conversation).
        """
        per_file: Dict[str, Dict[str, Any]] = {}
        weighted_sum = 0.0
        weight_total = 0.0

        for path, code in files.items():
            result = self.analyze(code, file_path=path)
            per_file[path] = result
            weight = max(1, len(code.split()))
            weighted_sum += result["ai_generated_probability"] * weight
            weight_total += weight

        overall_prob = weighted_sum / weight_total if weight_total else 0.0
        flagged_files = [
            p for p, r in per_file.items() if r["ai_generated_probability"] >= self.THRESHOLD
        ]

        return {
            "overall_ai_probability": round(overall_prob, 4),
            "overall_verdict": self._get_verdict(overall_prob),
            "flagged_files": flagged_files,
            "per_file": per_file,
        }

    # ------------------------------------------------------------------
    # PRIMARY Strategy: Perplexity / Burstiness via causal code LM
    # ------------------------------------------------------------------
    def _perplexity_score(self, code: str) -> Dict[str, Any]:
        tokenizer, model = _get_lm()
        if model is None or tokenizer is None:
            return {"available": False, "score": None, "perplexity": None, "burstiness": None}

        try:
            nlls = _token_nlls(code, tokenizer, model)
        except Exception as e:
            logger.warning(f"Perplexity scoring failed: {e}")
            return {"available": False, "score": None, "perplexity": None, "burstiness": None}

        if len(nlls) < self.MIN_TOKENS_FOR_PERPLEXITY:
            # Too little code to get a meaningful estimate -- don't guess.
            return {"available": False, "score": None, "perplexity": None, "burstiness": None}

        mean_nll = statistics.mean(nlls)
        perplexity = math.exp(min(mean_nll, 20))  # cap exponent to avoid overflow
        burstiness = statistics.pstdev(nlls)

        combined = self._bayesian_ai_probability(perplexity, burstiness)

        return {
            "available": True,
            "score": combined,
            "perplexity": perplexity,
            "burstiness": burstiness,
        }

    def _bayesian_ai_probability(self, perplexity: float, burstiness: float) -> float:
        """
        P(AI | perplexity, burstiness) via a simple Gaussian two-class
        model, using CALIBRATION's mean/std for each class (equal priors).
        This replaces a naive straight-line interpolation between two
        anchor points: modeling each class as a distribution means a
        value that falls outside the "typical" range for both classes
        still gets classified by which distribution it's relatively more
        likely under, instead of being clipped to a hard 0 or 1.
        """
        c = self.CALIBRATION
        log_p_human = (
            self._gaussian_logpdf(perplexity, c["ppl_human_mean"], c["ppl_human_std"])
            + self._gaussian_logpdf(burstiness, c["burst_human_mean"], c["burst_human_std"])
        )
        log_p_ai = (
            self._gaussian_logpdf(perplexity, c["ppl_ai_mean"], c["ppl_ai_std"])
            + self._gaussian_logpdf(burstiness, c["burst_ai_mean"], c["burst_ai_std"])
        )
        # Softmax the two log-likelihoods into a posterior probability.
        m = max(log_p_human, log_p_ai)
        p_h = math.exp(log_p_human - m)
        p_a = math.exp(log_p_ai - m)
        return p_a / (p_a + p_h)

    @staticmethod
    def _gaussian_logpdf(x: float, mean: float, std: float) -> float:
        std = max(std, 1e-6)
        return -0.5 * math.log(2 * math.pi * std ** 2) - ((x - mean) ** 2) / (2 * std ** 2)

    # ------------------------------------------------------------------
    # Secondary Strategy: Pattern Analysis
    # ------------------------------------------------------------------
    def _pattern_analysis(self, code: str) -> float:
        signals: List[float] = []

        if self._check_perfect_comments(code):
            signals.append(0.7)
        if self._check_verbose_names(code):
            signals.append(0.6)

        docstring_coverage = self._docstring_coverage(code)
        if docstring_coverage is not None:
            signals.append(docstring_coverage)

        inline_comment_density = self._inline_comment_density(code)
        signals.append(min(1.0, inline_comment_density * 2.0))

        return float(sum(signals) / len(signals)) if signals else 0.5

    def _check_perfect_comments(self, code: str) -> bool:
        comment_lines = [l.strip() for l in code.splitlines() if l.strip().startswith("#")]
        if not comment_lines:
            return False
        capitalised = sum(1 for c in comment_lines if c.lstrip("#").strip()[:1].isupper())
        return (capitalised / len(comment_lines)) > 0.85

    def _check_verbose_names(self, code: str) -> bool:
        identifiers = re.findall(r"\b([a-z][a-z0-9_]{15,})\b", code)
        return len(identifiers) > 5

    def _docstring_coverage(self, code: str) -> Optional[float]:
        """
        Fraction of functions/classes with docstrings. Returns None
        (not 0.0) when there's nothing to measure -- a file with no
        functions tells you nothing about AI authorship, it shouldn't
        silently count as "strongly human."
        NOTE: treat high coverage as weak evidence only -- many course
        rubrics require docstrings on every function for ALL students.
        """
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return None

        callables = [
            n for n in ast.walk(tree)
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        ]
        if not callables:
            return None

        with_docs = sum(1 for n in callables if ast.get_docstring(n))
        ratio = with_docs / len(callables)
        return ratio if ratio > 0.85 else ratio * 0.5

    def _inline_comment_density(self, code: str) -> float:
        lines = [l for l in code.splitlines() if l.strip()]
        if not lines:
            return 0.0
        inline = sum(1 for l in lines if "#" in l and not l.strip().startswith("#"))
        return inline / len(lines)

    # ------------------------------------------------------------------
    # Secondary Strategy: Style Consistency
    # ------------------------------------------------------------------
    def _style_consistency_check(self, code: str) -> float:
        """
        NOTE: weak signal in practice -- autoformatters (Black, autopep8)
        and IDE format-on-save push both human and AI code toward near-
        perfect consistency, so this mostly discriminates "unformatted
        vs formatted," not "human vs AI." Kept at low weight for this reason.
        """
        quote_consistency = self._check_quote_consistency(code)
        spacing_consistency = self._check_spacing_consistency(code)
        naming_consistency = self._naming_convention_consistency(code)

        avg_consistency = statistics.mean([quote_consistency, spacing_consistency, naming_consistency])

        if avg_consistency > 0.95:
            return 0.75
        elif avg_consistency > 0.85:
            return 0.55
        elif avg_consistency > 0.70:
            return 0.35
        else:
            return 0.20

    def _check_quote_consistency(self, code: str) -> float:
        single = len(re.findall(r"'[^']*'", code))
        double = len(re.findall(r'"[^"]*"', code))
        total = single + double
        return max(single, double) / total if total else 1.0

    def _check_spacing_consistency(self, code: str) -> float:
        spaced = len(re.findall(r"\w\s+=\s+\w", code))
        nospaced = len(re.findall(r"\w=\w", code))
        total = spaced + nospaced
        return max(spaced, nospaced) / total if total else 1.0

    def _naming_convention_consistency(self, code: str) -> float:
        identifiers = re.findall(r"\b([a-zA-Z_][a-zA-Z0-9_]{2,})\b", code)
        if not identifiers:
            return 1.0
        snake = sum(1 for i in identifiers if "_" in i and i == i.lower())
        return snake / len(identifiers)

    # ------------------------------------------------------------------
    # Secondary Strategy: Complexity Variance
    # ------------------------------------------------------------------
    def _complexity_analysis(self, code: str) -> float:
        try:
            import radon.complexity as rc

            blocks = rc.cc_visit(code)
            complexities = [b.complexity for b in blocks]
            if len(complexities) < 2:
                return 0.5
            variance = statistics.variance(complexities)
            if variance < 1.0:
                return 0.70
            elif variance < 3.0:
                return 0.55
            elif variance < 6.0:
                return 0.35
            else:
                return 0.20
        except Exception:
            return 0.5

    # ------------------------------------------------------------------
    # Secondary Strategy: Structural Analysis
    # ------------------------------------------------------------------
    def _structural_analysis(self, code: str) -> float:
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return 0.5

        signals: List[float] = []
        signals.append(self._type_hint_density(tree))
        signals.append(self._boilerplate_exception_handling(tree))
        signals.append(self._comprehension_preference(tree))
        return float(sum(signals) / len(signals)) if signals else 0.5

    def _type_hint_density(self, tree: ast.AST) -> float:
        """
        NOTE: weak signal for coursework -- many assignments (and mypy-
        enforcing rubrics) require type hints from every student.
        """
        typed_args = 0
        total_args = 0
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for arg in node.args.args:
                    if arg.arg != "self":
                        total_args += 1
                        if arg.annotation is not None:
                            typed_args += 1
        if total_args == 0:
            return 0.5
        ratio = typed_args / total_args
        return ratio if ratio > 0.8 else ratio * 0.5

    def _boilerplate_exception_handling(self, tree: ast.AST) -> float:
        try_blocks = [n for n in ast.walk(tree) if isinstance(n, ast.Try)]
        if not try_blocks:
            return 0.4
        generic_excepts = 0
        for t in try_blocks:
            for handler in t.handlers:
                if isinstance(handler.type, ast.Name) and handler.type.id == "Exception":
                    generic_excepts += 1
        ratio = generic_excepts / len(try_blocks)
        return ratio if ratio > 0.5 else 0.35

    def _comprehension_preference(self, tree: ast.AST) -> float:
        loops = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.For, ast.While)))
        comps = sum(
            1 for n in ast.walk(tree)
            if isinstance(n, (ast.ListComp, ast.DictComp, ast.SetComp, ast.GeneratorExp))
        )
        total = loops + comps
        if total == 0:
            return 0.5
        ratio = comps / total
        return min(1.0, ratio * 1.1)

    def _check_ai_boilerplate_text(self, code: str) -> bool:
        """Catches accidental copy-paste of chatbot conversational text."""
        boilerplate = [
            r"as an ai (language )?model",
            r"certainly! here is",
            r"here is the (code|implementation)",
            r"please note that",
            r"in this implementation",
            r"hope this helps",
            r"feel free to (ask|modify)",
            r"i cannot (fulfill|provide)",
        ]
        lower_code = code.lower()
        return any(re.search(b, lower_code) for b in boilerplate)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _get_verdict(self, probability: float) -> str:
        if probability >= 0.80:
            return "LIKELY_AI_GENERATED"
        elif probability >= 0.60:
            return "POSSIBLY_AI_ASSISTED"
        elif probability >= 0.40:
            return "UNCERTAIN"
        elif probability >= 0.20:
            return "POSSIBLY_HUMAN"
        else:
            return "LIKELY_HUMAN"

    def _calculate_confidence(
        self, detection_details: Dict[str, Any], ppl_available: bool, code: str
    ) -> float:
        """
        Confidence reflects whether the PRIMARY signal (perplexity) was
        actually available, not just whether secondary heuristics agree
        with each other -- agreement among weak heuristics alone should
        never look like high confidence.
        """
        base = 0.70 if ppl_available else 0.30

        token_estimate = len(code.split())
        if token_estimate < 40:
            base *= 0.6  # very short file -> not much evidence either way

        numeric_scores = [v for v in detection_details.values() if isinstance(v, (int, float))]
        if len(numeric_scores) >= 2:
            std = statistics.pstdev(numeric_scores)
            agreement_bonus = max(0.0, 0.15 - std)
            base = min(1.0, base + agreement_bonus)

        return base

    def _get_specific_flags(
        self, code: str, detection_details: Dict[str, Any], boilerplate_hit: bool
    ) -> List[str]:
        flags: List[str] = []

        if detection_details.get("perplexity_score") is not None:
            if detection_details["perplexity_score"] >= 0.70:
                flags.append(
                    f"Low perplexity/burstiness (ppl={detection_details.get('perplexity_raw')}, "
                    f"burstiness={detection_details.get('burstiness_raw')}) -- code is unusually "
                    f"predictable to the code LM"
                )
        else:
            flags.append("Perplexity model unavailable or file too short -- score based on weaker heuristics only")

        if detection_details.get("pattern_score", 0) >= 0.70:
            flags.append("AI-typical comment/naming patterns detected (weak signal, verify against rubric)")

        if detection_details.get("style_score", 0) >= 0.70:
            flags.append("Very high formatting consistency (weak signal -- check if autoformatter was used)")

        if detection_details.get("complexity_score", 0) >= 0.70:
            flags.append("Uniform function complexity (weak signal)")

        if detection_details.get("structural_score", 0) >= 0.75:
            flags.append("Heavy type-hinting / boilerplate exception handling (weak signal, check rubric requirements)")

        if boilerplate_hit:
            flags.append("Contains literal chatbot conversational text -- strong evidence of copy-paste from an AI tool")

        return flags

    def _empty_response(self, reason: str) -> Dict[str, Any]:
        return {
            "ai_generated_probability": 0.0,
            "verdict": "UNCERTAIN",
            "confidence": 0.0,
            "detection_details": {},
            "flags": [],
            "error": reason,
        }


# ---------------------------------------------------------------------------
# Calibration helper -- run this against YOUR labeled data before trusting
# absolute perplexity thresholds. This is not optional for production use.
# ---------------------------------------------------------------------------
def calibrate_from_samples(
    human_code_samples: List[str], ai_code_samples: List[str]
) -> Dict[str, float]:
    """
    Compute a CALIBRATION dict (mean + std per class) from labeled examples.

    Usage:
        human_files = [open(p).read() for p in glob("known_human/*.py")]
        ai_files = [open(p).read() for p in glob("known_ai/*.py")]
        calibration = calibrate_from_samples(human_files, ai_files)
        AICodeDetector.CALIBRATION = calibration   # or paste the values in directly

    You want at least ~30-50 files per class, drawn from the SAME
    assignment types and SAME AI tools (ChatGPT/Copilot/Claude/etc.)
    your platform will actually encounter, for this to be meaningful.
    Re-run whenever you change _LM_MODEL_NAME -- the numbers are only
    valid for the specific judge model they were measured with.
    """
    tokenizer, model = _get_lm()
    if model is None:
        raise RuntimeError("Code LM not available -- cannot calibrate.")

    def _stats(samples: List[str]) -> Tuple[float, float, float, float]:
        ppls, bursts = [], []
        for code in samples:
            nlls = _token_nlls(code, tokenizer, model)
            if len(nlls) < AICodeDetector.MIN_TOKENS_FOR_PERPLEXITY:
                continue
            ppls.append(math.exp(min(statistics.mean(nlls), 20)))
            bursts.append(statistics.pstdev(nlls))
        if not ppls:
            return (0.0, 1.0, 0.0, 1.0)
        ppl_std = statistics.pstdev(ppls) if len(ppls) > 1 else max(ppls[0] * 0.3, 0.5)
        burst_std = statistics.pstdev(bursts) if len(bursts) > 1 else max(bursts[0] * 0.3, 0.2)
        return (statistics.mean(ppls), ppl_std, statistics.mean(bursts), burst_std)

    h_ppl_mean, h_ppl_std, h_burst_mean, h_burst_std = _stats(human_code_samples)
    a_ppl_mean, a_ppl_std, a_burst_mean, a_burst_std = _stats(ai_code_samples)

    calibration = {
        "ppl_human_mean": h_ppl_mean, "ppl_human_std": h_ppl_std,
        "ppl_ai_mean": a_ppl_mean, "ppl_ai_std": a_ppl_std,
        "burst_human_mean": h_burst_mean, "burst_human_std": h_burst_std,
        "burst_ai_mean": a_burst_mean, "burst_ai_std": a_burst_std,
    }

    if a_ppl_mean >= h_ppl_mean:
        logger.warning(
            "Calibration warning: measured AI-sample perplexity (%.2f) is not "
            "lower than human-sample perplexity (%.2f). This usually means "
            "the judge model (%s) is too weak to distinguish your AI samples "
            "from human code -- consider a stronger model.",
            a_ppl_mean, h_ppl_mean, _LM_MODEL_NAME,
        )

    return calibration