"""
AI Engine - AI-Generated Code Detector

Uses 4 detection strategies:
  1. ML Model (RoBERTa-based, optional / lazy-loaded)
  2. Pattern Analysis (AI-typical comment/naming conventions)
  3. Style Consistency (humans have ~5-15% inconsistency; AI is near-perfect)
  4. Complexity Variance (AI produces uniformly moderate complexity)
"""
import ast
import logging
import re
import statistics
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# numpy is optional – used only for convenience; pure-Python fallbacks provided
try:
    import numpy as _np
    _HAS_NUMPY = True
except ImportError:  # pragma: no cover
    _np = None  # type: ignore[assignment]
    _HAS_NUMPY = False


# ---------------------------------------------------------------------------
# Singleton ML model loader
# ---------------------------------------------------------------------------
_ml_model_instance: Optional[Any] = None
_ml_tokenizer_instance: Optional[Any] = None


def _get_ml_model():
    """Lazy-load RoBERTa detector (CPU-safe)."""
    global _ml_model_instance, _ml_tokenizer_instance
    if _ml_model_instance is not None:
        return _ml_tokenizer_instance, _ml_model_instance

    try:
        import torch
        from transformers import AutoModelForSequenceClassification, AutoTokenizer

        model_name = "roberta-base-openai-detector"
        logger.info(f"Loading AI detection model: {model_name}")
        _ml_tokenizer_instance = AutoTokenizer.from_pretrained(model_name)
        _ml_model_instance = AutoModelForSequenceClassification.from_pretrained(model_name)
        _ml_model_instance.eval()
        logger.info("AI detection model loaded successfully.")
    except Exception as e:
        logger.warning(f"AI detection model unavailable ({e}). Falling back to heuristics.")
        _ml_model_instance = None
        _ml_tokenizer_instance = None

    return _ml_tokenizer_instance, _ml_model_instance


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------
class AICodeDetector:
    """
    Detects if code was generated by AI tools (ChatGPT, GitHub Copilot, etc.).
    Uses 4 detection strategies: ML model, pattern analysis, style consistency,
    and complexity variance.
    """

    WEIGHTS = {
        "ml_model": 0.40,
        "pattern_analysis": 0.30,
        "style_consistency": 0.20,
        "complexity_analysis": 0.10,
    }

    THRESHOLD = 0.75  # Probability >= this → flagged as AI-generated

    def analyze(self, code: str, file_path: Optional[str] = None) -> Dict[str, Any]:
        """
        Comprehensive AI-generated code detection.

        Args:
            code: Source code string.
            file_path: Optional path (used for logging).

        Returns:
            Dict with probability, verdict, confidence, detection details, and flags.
        """
        if not code or not code.strip():
            return self._empty_response("Empty code provided")

        try:
            ml_score = self._ml_detection(code)
            pattern_score = self._pattern_analysis(code)
            style_score = self._style_consistency_check(code)
            complexity_score = self._complexity_analysis(code)

            detection_details: Dict[str, float] = {
                "ml_detection": float(round(ml_score, 4)),
                "pattern_score": float(round(pattern_score, 4)),
                "style_score": float(round(style_score, 4)),
                "complexity_score": float(round(complexity_score, 4)),
            }

            ai_probability = (
                ml_score * self.WEIGHTS["ml_model"]
                + pattern_score * self.WEIGHTS["pattern_analysis"]
                + style_score * self.WEIGHTS["style_consistency"]
                + complexity_score * self.WEIGHTS["complexity_analysis"]
            )
            # Clamp to [0, 1] without requiring numpy
            ai_probability = float(max(0.0, min(1.0, ai_probability)))
            ai_probability = float(round(ai_probability, 4))

            confidence = self._calculate_confidence(detection_details)
            verdict = self._get_verdict(ai_probability)
            flags = self._get_specific_flags(code, detection_details)

            return {
                "ai_generated_probability": ai_probability,
                "verdict": verdict,
                "confidence": float(round(confidence, 4)),
                "detection_details": detection_details,
                "flags": flags,
            }

        except Exception as e:
            logger.error(f"AI detection error for {file_path}: {e}")
            return self._empty_response(str(e))

    # ------------------------------------------------------------------
    # Strategy 1: ML Model
    # ------------------------------------------------------------------
    def _ml_detection(self, code: str) -> float:
        """
        Use RoBERTa model to detect AI-generated code.
        Tokenizes the first 512 tokens and runs inference.
        Returns 0.5 (neutral) when model is unavailable.
        """
        tokenizer, model = _get_ml_model()
        if model is None or tokenizer is None:
            return 0.5  # Neutral – heuristics will dominate

        try:
            import torch

            inputs = tokenizer(
                code,
                return_tensors="pt",
                max_length=512,
                truncation=True,
                padding=True,
            )
            with torch.no_grad():
                logits = model(**inputs).logits
                probs = torch.softmax(logits, dim=-1)
                # Label 1 = "generated", label 0 = "real"
                ai_prob = float(probs[0][1].item())
            return ai_prob
        except Exception as e:
            logger.warning(f"ML inference failed: {e}")
            return 0.5

    # ------------------------------------------------------------------
    # Strategy 2: Pattern Analysis
    # ------------------------------------------------------------------
    def _pattern_analysis(self, code: str) -> float:
        """
        Analyze code for patterns typical of AI-generated output.
        Returns a 0-1 score (higher = more AI-like).
        """
        signals: List[float] = []

        # Perfect comment formatting
        if self._check_perfect_comments(code):
            signals.append(0.85)

        # Overly verbose names
        if self._check_verbose_names(code):
            signals.append(0.75)

        # Comprehensive docstrings on ALL functions/classes
        docstring_coverage = self._docstring_coverage(code)
        signals.append(docstring_coverage)

        # Check for explanatory inline comments typical of AI
        inline_comment_density = self._inline_comment_density(code)
        signals.append(min(1.0, inline_comment_density * 2.5))

        # Pure-Python mean (no numpy dependency)
        return float(sum(signals) / len(signals)) if signals else 0.5

    def _check_perfect_comments(self, code: str) -> bool:
        """Check for AI-style perfectly formatted comments."""
        comment_lines = [
            l.strip() for l in code.splitlines() if l.strip().startswith("#")
        ]
        if not comment_lines:
            return False
        # AI comments tend to start with capital letter and end without period
        capitalised = sum(
            1 for c in comment_lines if c.lstrip("#").strip()[:1].isupper()
        )
        return (capitalised / len(comment_lines)) > 0.85

    def _check_verbose_names(self, code: str) -> bool:
        """Check for AI-style overly descriptive identifiers."""
        identifiers = re.findall(r"\b([a-z][a-z0-9_]{15,})\b", code)
        if not identifiers:
            return False
        return len(identifiers) > 5  # More than 5 very long names is suspicious

    def _docstring_coverage(self, code: str) -> float:
        """Fraction of functions/classes that have docstrings (AI tends to 100%)."""
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return 0.5

        callables = [
            n
            for n in ast.walk(tree)
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        ]
        if not callables:
            return 0.0

        with_docs = sum(
            1 for n in callables if ast.get_docstring(n)
        )
        ratio = with_docs / len(callables)
        # Humans rarely document 100%; very suspicious if > 90%
        return ratio if ratio > 0.85 else ratio * 0.5

    def _inline_comment_density(self, code: str) -> float:
        """Fraction of code lines with an inline comment."""
        lines = [l for l in code.splitlines() if l.strip()]
        if not lines:
            return 0.0
        inline = sum(1 for l in lines if "#" in l and not l.strip().startswith("#"))
        return inline / len(lines)

    # ------------------------------------------------------------------
    # Strategy 3: Style Consistency
    # ------------------------------------------------------------------
    def _style_consistency_check(self, code: str) -> float:
        """
        Check if style is TOO consistent (a strong AI indicator).
        Humans have ~5-15% natural inconsistency.
        Returns 0-1   (higher = more AI-like).
        """
        quote_consistency = self._check_quote_consistency(code)
        spacing_consistency = self._check_spacing_consistency(code)
        naming_consistency = self._naming_convention_consistency(code)

        avg_consistency = float(
            statistics.mean([quote_consistency, spacing_consistency, naming_consistency])
        )

        # Consistency > 0.95 → very suspicious
        if avg_consistency > 0.95:
            return 0.9
        elif avg_consistency > 0.85:
            return 0.65
        elif avg_consistency > 0.70:
            return 0.40
        else:
            return 0.20

    def _check_quote_consistency(self, code: str) -> float:
        """Calculate string-quote style consistency (0-1)."""
        single = len(re.findall(r"'[^']*'", code))
        double = len(re.findall(r'"[^"]*"', code))
        total = single + double
        if total == 0:
            return 1.0
        return max(single, double) / total

    def _check_spacing_consistency(self, code: str) -> float:
        """Calculate operator spacing consistency (0-1)."""
        spaced = len(re.findall(r"\w\s+=\s+\w", code))
        nospaced = len(re.findall(r"\w=\w", code))
        total = spaced + nospaced
        if total == 0:
            return 1.0
        return max(spaced, nospaced) / total

    def _naming_convention_consistency(self, code: str) -> float:
        """Check how uniformly snake_case is used (0-1)."""
        identifiers = re.findall(r"\b([a-zA-Z_][a-zA-Z0-9_]{2,})\b", code)
        if not identifiers:
            return 1.0
        snake = sum(1 for i in identifiers if "_" in i and i == i.lower())
        return snake / len(identifiers)

    # ------------------------------------------------------------------
    # Strategy 4: Complexity Variance
    # ------------------------------------------------------------------
    def _complexity_analysis(self, code: str) -> float:
        """
        Detect uniform cyclomatic complexity (AI indicator).
        Low variance across functions = AI-generated.
        Returns 0-1 (higher = more AI-like / more uniform).
        """
        try:
            import radon.complexity as rc

            blocks = rc.cc_visit(code)
            complexities = [b.complexity for b in blocks]

            if len(complexities) < 2:
                return 0.5  # Not enough data

            variance = statistics.variance(complexities)

            # Very low variance (< 2) across functions is suspicious
            if variance < 1.0:
                return 0.85
            elif variance < 3.0:
                return 0.60
            elif variance < 6.0:
                return 0.35
            else:
                return 0.15

        except Exception:
            return 0.5

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _get_verdict(self, probability: float) -> str:
        if probability >= 0.80:
            return "LIKELY_AI_GENERATED"
        elif probability >= 0.60:
            return "POSSIBLY_AI_ASSISTED"
        elif probability >= 0.40:
            return "UNCERTAIN"
        elif probability >= 0.20:
            return "POSSIBLY_HUMAN"
        else:
            return "LIKELY_HUMAN"

    def _calculate_confidence(self, detection_details: Dict[str, float]) -> float:
        """
        Confidence = 1 - normalised standard deviation across strategy scores.
        Low variance in scores → strategies agree → high confidence.
        """
        scores = list(detection_details.values())
        if len(scores) < 2:
            return 0.5
        std = statistics.stdev(scores)
        # Normalise: std of 0 → confidence 1.0 ; std of 0.5 (max on 0-1) → confidence 0.0
        confidence = max(0.0, 1.0 - (std * 2))
        return confidence

    def _get_specific_flags(
        self, code: str, detection_details: Dict[str, float]
    ) -> List[str]:
        """Identify specific red flags found in the code."""
        flags: List[str] = []

        if detection_details.get("pattern_score", 0) >= 0.70:
            flags.append("AI-typical comment patterns detected")

        if self._check_verbose_names(code):
            flags.append("Overly verbose variable/function names detected")

        if detection_details.get("style_score", 0) >= 0.70:
            flags.append("Suspiciously perfect code formatting")

        if detection_details.get("complexity_score", 0) >= 0.70:
            flags.append("Uniform complexity across functions (low variance)")

        if self._docstring_coverage(code) >= 0.90:
            flags.append("All functions have docstrings (atypical for human code)")

        if detection_details.get("ml_detection", 0.5) >= 0.70:
            flags.append("ML model classifies code as likely AI-generated")

        return flags

    def _empty_response(self, reason: str) -> Dict[str, Any]:
        return {
            "ai_generated_probability": 0.0,
            "verdict": "UNCERTAIN",
            "confidence": 0.0,
            "detection_details": {
                "ml_detection": 0.5,
                "pattern_score": 0.0,
                "style_score": 0.0,
                "complexity_score": 0.0,
            },
            "flags": [],
            "error": reason,
        }
